In [1]:
import pandas as pd
import numpy as np
from utils import set_pretty_prints

set_pretty_prints()

In [2]:
df = pd.read_csv('../data/imobiliare_bucuresti.csv')

In [3]:
df

Unnamed: 0  nr cam     mp  parter  et1-2  et3+  etaj max  typ_decom  bloc nou  Price/Surface   Price                                                                                                                                      WebPage
0              1       2  56.00       0      1     0         2          1         1         639.29   35800              https://www.imobiliare.ro/vanzare-apartamente/bucuresti/rahova/apartament-de-vanzare-2-camere-XAU700006?lista=2349706&listing=1
1              2       2  57.00       0      1     0         2          0         1         628.07   35800              https://www.imobiliare.ro/vanzare-apartamente/bucuresti/rahova/apartament-de-vanzare-2-camere-XAG00001O?lista=2349706&listing=1
2              3       2  67.00       0      1     0         2          1         1         591.04   39600              https://www.imobiliare.ro/vanzare-apartamente/bucuresti/rahova/apartament-de-vanzare-2-camere-XAG00001K?lista=2349706&listing=1
3              4       1  48.00       0      1     0         2          1         1         620.83   29800                        https://www.imobiliare.ro/vanzare-garsoniere/bucuresti/rahova/garsoniera-de-vanzare-XAG00001J?lista=2349706&listing=1
4              5       3  89.60       0      0     1         3          1         1        1260.04  112900  https://www.imobiliare.ro/vanzare-apartamente/bucuresti/p-ta-presei-libere/apartament-de-vanzare-3-camere-XB0V00003?lista=2349706&listing=1
...          ...     ...    ...     ...    ...   ...       ...        ...       ...            ...     ...                                                                                                                                          ...
9892        9894       4  90.00       0      0     1         8          0         0         944.44   85000            https://www.imobiliare.ro/vanzare-apartamente/bucuresti/crangasi/apartament-de-vanzare-4-camere-X5LL10023?lista=2349706&listing=1
9893        9895       3  85.00       0      0     1         8          1         0        1588.22  134999             https://www.imobiliare.ro/vanzare-apartamente/bucuresti/central/apartament-de-vanzare-3-camere-X9I6100JP?lista=2349706&listing=1
9894        9896       2  48.00       0      0     1         4          0         0        1229.17   59000            https://www.imobiliare.ro/vanzare-apartamente/bucuresti/apusului/apartament-de-vanzare-2-camere-XBJG000HP?lista=2349706&listing=1
9895        9897       4  83.81       0      0     1         3          1         1        1312.49  110000      https://www.imobiliare.ro/vanzare-apartamente/bucuresti/theodor-pallady/penthouse-de-vanzare-4-camere-XANO10193?lista=2349706&listing=1
9896        9898       1  35.00       0      0     1         4          1         1        1757.14   61500                   https://www.imobiliare.ro/vanzare-garsoniere/bucuresti/politehnica/garsoniera-de-vanzare-X17L10040?lista=2349706&listing=1

[9897 rows x 12 columns]

In [4]:
df = df.iloc[:,1:-1]
df

nr cam     mp  parter  et1-2  et3+  etaj max  typ_decom  bloc nou  Price/Surface   Price
0          2  56.00       0      1     0         2          1         1         639.29   35800
1          2  57.00       0      1     0         2          0         1         628.07   35800
2          2  67.00       0      1     0         2          1         1         591.04   39600
3          1  48.00       0      1     0         2          1         1         620.83   29800
4          3  89.60       0      0     1         3          1         1        1260.04  112900
...      ...    ...     ...    ...   ...       ...        ...       ...            ...     ...
9892       4  90.00       0      0     1         8          0         0         944.44   85000
9893       3  85.00       0      0     1         8          1         0        1588.22  134999
9894       2  48.00       0      0     1         4          0         0        1229.17   59000
9895       4  83.81       0      0     1         3          1         1        1312.49  110000
9896       1  35.00       0      0     1         4          1         1        1757.14   61500

[9897 rows x 10 columns]

In [5]:
TARGET_COLUMN = 'Price'

In [72]:
X_raw = df.values[:,:-2]
y = df[TARGET_COLUMN].values.reshape(-1,1)
X_raw[:20]

array([[  2.  ,  56.  ,   0.  ,   1.  ,   0.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,  57.  ,   0.  ,   1.  ,   0.  ,   2.  ,   0.  ,   1.  ],
       [  2.  ,  67.  ,   0.  ,   1.  ,   0.  ,   2.  ,   1.  ,   1.  ],
       [  1.  ,  48.  ,   0.  ,   1.  ,   0.  ,   2.  ,   1.  ,   1.  ],
       [  3.  ,  89.6 ,   0.  ,   0.  ,   1.  ,   3.  ,   1.  ,   1.  ],
       [  2.  ,  65.  ,   0.  ,   1.  ,   0.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,  46.  ,   0.  ,   0.  ,   1.  ,   4.  ,   1.  ,   1.  ],
       [  6.  , 334.  ,   0.  ,   0.  ,   1.  ,  10.  ,   1.  ,   1.  ],
       [  3.  , 104.26,   0.  ,   0.  ,   1.  ,  11.  ,   1.  ,   1.  ],
       [  2.  ,  65.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,   1.  ],
       [  2.  ,  46.  ,   0.  ,   0.  ,   1.  ,   3.  ,   1.  ,   1.  ],
       [  1.  ,  43.02,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,   1.  ],
       [  3.  ,  80.23,   0.  ,   0.  ,   1.  ,   3.  ,   1.  ,   1.  ],
       [  1.  ,  30.  ,   1.  ,   0.  ,   0.  ,   0

In [73]:
X_min = X_raw.min(0)
X_max = X_raw.max(0)
X_range = X_max - X_min
X_mean = X_raw.mean(0)
X_std = X_raw.std(0)
X_raw.shape

(9897, 8)

In [74]:
X_denom = X_mean
X_nom = X_std
X = (X_raw - X_denom) / X_nom
X[:20]

array([[-0.53, -0.44, -0.38,  1.33, -1.03, -0.47,  0.63,  0.83],
       [-0.53, -0.42, -0.38,  1.33, -1.03, -0.47, -1.59,  0.83],
       [-0.53, -0.17, -0.38,  1.33, -1.03, -0.47,  0.63,  0.83],
       [-1.58, -0.64, -0.38,  1.33, -1.03, -0.47,  0.63,  0.83],
       [ 0.52,  0.4 , -0.38, -0.75,  0.98, -0.12,  0.63,  0.83],
       [-0.53, -0.22, -0.38,  1.33, -1.03, -0.47,  0.63,  0.83],
       [-0.53, -0.69, -0.38, -0.75,  0.98,  0.24,  0.63,  0.83],
       [ 3.68,  6.48, -0.38, -0.75,  0.98,  2.36,  0.63,  0.83],
       [ 0.52,  0.76, -0.38, -0.75,  0.98,  2.72,  0.63,  0.83],
       [-0.53, -0.22, -0.38,  1.33, -1.03, -0.83, -1.59,  0.83],
       [-0.53, -0.69, -0.38, -0.75,  0.98, -0.12,  0.63,  0.83],
       [-1.58, -0.76,  2.64, -0.75, -1.03, -1.18,  0.63,  0.83],
       [ 0.52,  0.16, -0.38, -0.75,  0.98, -0.12,  0.63,  0.83],
       [-1.58, -1.09,  2.64, -0.75, -1.03, -1.18,  0.63,  0.83],
       [-0.53, -0.19, -0.38,  1.33, -1.03, -0.47,  0.63,  0.83],
       [ 1.57,  0.42, -0.

In [75]:
prc_test = 0.25

In [76]:
from sklearn.model_selection import train_test_split
x_train,x_t, y_train, y_t = train_test_split(X, y, test_size=prc_test, random_state=1234)
x_dev,x_test, y_dev,y_test = train_test_split(x_t, y_t, test_size=0.5, random_state=1234)
print("Train/Dev/Test: {}/{}/{}".format(x_train.shape[0], x_dev.shape[0], x_test.shape[0]))

Train/Dev/Test: 7422/1237/1238


## Now the PyTorch stuff

### for data: 
    tensorize -> maybe load to GPU -> create dataset -> create data loader for batches
### for model: 
    define model as nn.Model
### for actual training: 
    run batch gradient descent

In [77]:
import torch as th
th.__version__

'1.4.0'

In [78]:
target_device = th.device('cuda')
print("{:,.1f}M".format(th.cuda.memory_allocated() / 1024**2))

0.9M


In [79]:
th_x_train = th.tensor(x_train, dtype=th.float32)
th_x_dev = th.tensor(x_dev, dtype=th.float32)
th_x_test = th.tensor(x_test, dtype=th.float32)
th_y_train = th.tensor(y_train, dtype=th.float32)
th_y_dev = th.tensor(y_dev, dtype=th.float32)
th_y_test = th.tensor(y_test, dtype=th.float32)

In [80]:
th_x_train

tensor([[-0.5321, -0.5901, -0.3792,  ...,  0.9450,  0.6273,  0.8281],
        [ 0.5201,  0.5799, -0.3792,  ..., -0.4742,  0.6273,  0.8281],
        [-0.5321, -0.0922, -0.3792,  ..., -0.1194,  0.6273,  0.8281],
        ...,
        [ 0.5201,  0.7790, -0.3792,  ..., -0.1194,  0.6273, -1.2076],
        [ 0.5201, -0.0855, -0.3792,  ...,  1.2998,  0.6273,  0.8281],
        [ 1.5722,  1.9241, -0.3792,  ...,  0.9450,  0.6273,  0.8281]])

In [81]:
th_y_train

tensor([[179000.],
        [166636.],
        [ 64500.],
        ...,
        [195000.],
        [134900.],
        [485000.]])

In [82]:
th_x_train = th_x_train.to(target_device)
th_x_dev = th_x_dev.to(target_device)
th_x_test = th_x_test.to(target_device)
th_y_train = th_y_train.to(target_device)
th_y_dev = th_y_dev.to(target_device)
th_y_test = th_y_test.to(target_device)
th_x_train

tensor([[-0.5321, -0.5901, -0.3792,  ...,  0.9450,  0.6273,  0.8281],
        [ 0.5201,  0.5799, -0.3792,  ..., -0.4742,  0.6273,  0.8281],
        [-0.5321, -0.0922, -0.3792,  ..., -0.1194,  0.6273,  0.8281],
        ...,
        [ 0.5201,  0.7790, -0.3792,  ..., -0.1194,  0.6273, -1.2076],
        [ 0.5201, -0.0855, -0.3792,  ...,  1.2998,  0.6273,  0.8281],
        [ 1.5722,  1.9241, -0.3792,  ...,  0.9450,  0.6273,  0.8281]],
       device='cuda:0')

In [83]:
print("{:,.1f}M".format(th.cuda.memory_allocated() / 1024**2))

1.1M


In [84]:
th_ds = th.utils.data.TensorDataset(th_x_train, th_y_train)

In [85]:
th_ds

In [86]:
BATCH_SIZE = 32
N_BATCHES = x_train.shape[0] // BATCH_SIZE
N_BATCHES

231

In [87]:
th_loader = th.utils.data.DataLoader(th_ds, batch_size=BATCH_SIZE)

In [88]:
for th_x_batch, th_y_batch in th_loader:
    print(th_x_batch, th_y_batch)
    break

tensor([[-0.5321, -0.5901, -0.3792, -0.7530,  0.9753,  0.9450,  0.6273,  0.8281],
        [ 0.5201,  0.5799, -0.3792,  1.3281, -1.0253, -0.4742,  0.6273,  0.8281],
        [-0.5321, -0.0922, -0.3792, -0.7530,  0.9753, -0.1194,  0.6273,  0.8281],
        [ 0.5201,  0.1069, -0.3792, -0.7530,  0.9753,  1.2998, -1.5940, -1.2076],
        [ 0.5201,  0.1318, -0.3792,  1.3281, -1.0253, -0.4742,  0.6273,  0.8281],
        [-0.5321, -0.2665, -0.3792, -0.7530,  0.9753, -0.1194,  0.6273,  0.8281],
        [ 0.5201,  0.1318, -0.3792,  1.3281, -1.0253, -0.8289,  0.6273,  0.8281],
        [ 0.5201, -0.2914, -0.3792, -0.7530,  0.9753, -0.1194, -1.5940, -1.2076],
        [ 0.5201,  0.7292, -0.3792, -0.7530,  0.9753,  2.3641,  0.6273,  0.8281],
        [ 0.5201,  0.4056, -0.3792,  1.3281, -1.0253, -0.8289,  0.6273, -1.2076],
        [-1.5843, -1.0630, -0.3792,  1.3281, -1.0253, -0.4742,  0.6273,  0.8281],
        [ 2.6244,  1.5258, -0.3792, -0.7530,  0.9753,  0.5902,  0.6273,  0.8281],
        [-0.5321

In [89]:
# now we just inherit torch.nn.Module and voila :)
class ImobiliareNN(th.nn.Module):
    def __init__(self,n_inputs=8, n_outputs1=64, n_outputs2=16):
        super().__init__()
        self.transform_1 = th.nn.Linear(n_inputs,n_outputs1)
        self.non_lin_1 = th.nn.ReLU() # max(0, input)
        self.transform_2 = th.nn.Linear(n_outputs1,n_outputs2)
        self.non_lin_2 = th.nn.ReLU() # max(0, input)    
        # self.drop = th.nn.Dropout(0.5)
        self.readout = th.nn.Linear(n_outputs2, 1)
    
    def forward(self, th_input):
        th_x = self.transform_1(th_input)
        th_x = self.non_lin_1(th_x)
        th_x = self.transform_2(th_x)
        th_x = self.non_lin_2(th_x)
        # th_x  = self.drop(th_x)
        th_x = self.readout(th_x)
        return th_x

In [194]:
th.manual_seed(123)
imob_nn = ImobiliareNN()
imob_nn = imob_nn.to(target_device)
imob_nn

ImobiliareNN(
  (transform_1): Linear(in_features=8, out_features=64, bias=True)
  (non_lin_1): ReLU()
  (transform_2): Linear(in_features=64, out_features=16, bias=True)
  (non_lin_2): ReLU()
  (readout): Linear(in_features=16, out_features=1, bias=True)
)

In [195]:
print(imob_nn.transform_1.bias)

Parameter containing:
tensor([ 0.0651, -0.3496,  0.0408, -0.1167, -0.0268,  0.2031, -0.1217, -0.2678,
         0.0214, -0.0985, -0.1649, -0.1080, -0.2005,  0.3103,  0.0243, -0.1876,
         0.2254,  0.0547,  0.2030,  0.2726,  0.3494, -0.0916,  0.0105, -0.2049,
         0.3226,  0.1125, -0.0585,  0.0886,  0.3508,  0.1440,  0.1717,  0.3264,
         0.0151,  0.0017,  0.0877, -0.3268,  0.1236, -0.0027, -0.0169,  0.0203,
         0.3132,  0.1015, -0.3203,  0.3275,  0.2156,  0.1784,  0.1459,  0.0345,
        -0.1952,  0.2266, -0.2642, -0.2138,  0.0009, -0.2743,  0.3207,  0.3513,
         0.1762,  0.2158, -0.3425,  0.3051,  0.0621, -0.2233, -0.2469,  0.0852],
       device='cuda:0', requires_grad=True)


In [196]:
print(imob_nn.transform_1.bias.grad)

None


In [197]:
th_optim = th.optim.SGD(params=imob_nn.parameters(), lr=0.004) # the bigger the lr the faster the convergenge - but risky
EPOCHS = 5
def predict(th_x, th_y=None):
    # next line is not required for our structure (no Dropout)
    imob_nn.eval() # tell the network to use its modules in evaluation mode (Dropout, BN, etc)
    with th.no_grad():
        th_preds = imob_nn(th_x)
        if th_y is not None:
            th_res = th_preds - th_y
            th_mae = th.mean(th.abs(th_res))
            print("MAE: {:.2f}".format(th_mae))
            res = th_mae.cpu().numpy()
        else:
            res = th_preds.cpu().numpy()
    # next line is not required for our structure (no Dropout)
    imob_nn.train() # # tell the network to use its modules in train mode (Dropout, BN, etc)
    return res
    
best_dev_mae = np.inf
for epoch in range(EPOCHS):    
    for th_x_batch, th_y_batch in th_loader:
        th_y_pred = imob_nn(th_x_batch)
        th_loss_batch = th.abs(th_y_batch - th_y_pred)
        th_loss = th_loss_batch.mean()
        th_loss.backward()
        #print(imob_nn.transform_1.bias.grad)
        #break
        th_optim.step()
        th_optim.zero_grad()
    # done epoch
    print("Epoch {} done. Calculating dev MAE...".format(epoch + 1))
    epoch_mae = predict(th_x_dev, th_y_dev)       
    if epoch_mae < best_dev_mae:
        best_epoch_based_on_dev = epoch +1
        best_dev_mae = epoch_mae
        # now you can save your model coefs

# now you can load your best model coef
print("Based on dev-set our best model is at epoch {} with MAE: {:.1f}".format(best_epoch_based_on_dev, best_dev_mae))
# however: NOW you have to "test on test"
# so load your best model and predict
predict(th_x_test, th_y_test)

Epoch 1 done. Calculating dev MAE...
MAE: 137365.16
Epoch 2 done. Calculating dev MAE...
MAE: 46765.52
Epoch 3 done. Calculating dev MAE...
MAE: 43359.80
Epoch 4 done. Calculating dev MAE...
MAE: 46110.09
Epoch 5 done. Calculating dev MAE...
MAE: 47191.24
Based on dev-set our best model is at epoch 3 with MAE: 43359.8
MAE: 50458.98


array(50458.98, dtype=float32)

In [198]:
th.no_grad

torch.autograd.grad_mode.no_grad

In [199]:
th_y_batch.cpu

<function Tensor.cpu>

In [125]:
th.random.seed

<function torch.random.seed()>